/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#131b2e",
        "on-primary-fixed-variant": "#004b6f",
        "on-surface": "#131b2e",
        "tertiary-fixed": "#d3e4fe",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#c4c7c9",
        "primary": "#006492",
        "on-secondary-fixed-variant": "#444749",
        "on-tertiary-container": "#1d2e42",
        "primary-fixed": "#cae6ff",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed": "#e0e3e5",
        "on-secondary-container": "#626567",
        "inverse-surface": "#283044",
        "on-surface-variant": "#3f4850",
        "surface-tint": "#006492",
        "tertiary": "#505f76",
        "on-tertiary-fixed-variant": "#38485d",
        "secondary": "#5c5f61",
        "on-secondary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-container-low": "#f2f3ff",
        "inverse-primary": "#8ccdff",
        "on-primary-fixed": "#001e2f",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed": "#0b1c30",
        "tertiary-container": "#8595ad",
        "surface-dim": "#d2d9f4",
        "primary-container": "#2d9cdb",
        "inverse-on-surface": "#eef0ff",
        "surface": "#faf8ff",
        "on-error": "#ffffff",
        "outline-variant": "#bec7d1",
        "outline": "#6f7881",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#8ccdff",
        "on-primary-container": "#003049",
        "surface-variant": "#dae2fd",
        "surface-bright": "#faf8ff",
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "background": "#faf8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-xs": "8px",
        "stack-sm": "16px",
        "stack-xl": "128px",
        "container-max": "1120px",
        "stack-lg": "64px",
        "gutter": "24px",
        "unit": "4px",
        "stack-md": "32px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "display-lg-mobile": ["DM Sans"],
        "display-lg": ["DM Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["DM Sans"],
        "headline-md": ["DM Sans"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.5", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "1.3", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
