import React, { useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, ChevronDown, ExternalLink } from 'lucide-react'
import { MagneticButton } from './Motion'

const filters = ['All', 'Power BI', 'Python', 'SQL', 'Streamlit', 'Web']

const createSvgImage = (title, accent, secondary, subtitle = 'Data-driven portfolio project') => {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><rect width="1200" height="800" rx="36" fill="#0F172A"/><rect x="40" y="40" width="1120" height="720" rx="28" fill="url(#grad)"/><circle cx="930" cy="220" r="140" fill="${secondary}" opacity="0.28"/><circle cx="260" cy="620" r="180" fill="${accent}" opacity="0.22"/><path d="M140 610c90-120 180-180 292-180 120 0 201 58 304 58 94 0 183-48 260-132" stroke="white" stroke-width="18" fill="none" stroke-linecap="round" opacity="0.9"/><text x="180" y="92" fill="white" font-family="Segoe UI, Arial, sans-serif" font-size="36" font-weight="700">${title}</text><text x="180" y="132" fill="rgba(255,255,255,0.82)" font-family="Segoe UI, Arial, sans-serif" font-size="24">${subtitle}</text><defs><linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${accent}"/><stop offset="100%" stop-color="${secondary}"/></linearGradient></defs></svg>`
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`
}

const projects = [
  { title: 'Earthquake Risk Analysis', tag: 'Python', category: 'Python', description: 'A Python workflow for collecting, cleaning, and visualizing earthquake event data from the USGS API.', imageSrc: createSvgImage('Earthquake Analysis', '#f59e0b', '#dc2626'), link: 'https://github.com/Nima-vd/Earthquake_analysis', demo: null, problem: 'Make earthquake activity easier to inspect through a repeatable analytical workflow.', dataset: 'USGS earthquake event data.', tools: 'Python, data collection, cleaning, and visualization.', methodology: 'Collect source data, prepare it for analysis, then visualize patterns and risk signals.', dataCleaning: 'Standardize API fields and prepare records for consistent filtering and comparison.', analysis: 'Explore activity by location, timing, and earthquake characteristics.', insights: 'The workflow creates a repeatable view of seismic activity and risk patterns.', value: 'Supports clearer exploration of hazard trends and a foundation for future risk reporting.', challenges: 'Working with changing API responses while maintaining a consistent analysis pipeline.', learned: 'How a reliable data pipeline improves the quality of downstream visual analysis.' },
  { title: 'Road Safety Reporting Platform', tag: 'Web', category: 'Web', description: 'A final-year role based(Citizen, Staff and Admin) project web based application for structured incident reporting and safety review with a database-backed workflow.', imageSrc: createSvgImage('Road Safety Platform', '#14b8a6', '#2563eb', 'Web reporting application'), link: 'https://github.com/Nima-vd/sadaksachet', demo: null, problem: 'Create a practical digital experience for collecting, managing and reviewing safety incidents.', dataset: 'User-generated incident reports; production dataset details are not published.', tools: 'Full-stack web development and database-backed application design.', methodology: 'Translate reporting needs into an efficient workflow for capturing, storing, and reviewing incidents.', dataCleaning: 'The current portfolio does not publish a production data-cleaning workflow for this application.', analysis: 'The project focuses on reporting flow, data capture, and application structure rather than analytics publication.', insights: 'The project demonstrates product thinking and operational data management.', value: 'Provides a foundation for data-informed incident review and safer reporting processes.', challenges: 'Balancing user reporting needs with a clear, practical application flow.', learned: 'How product requirements shape technical and data decisions.' },
  { title: 'Data Professional Survey Breakdown', tag: 'Power BI', category: 'Power BI', description: 'An interactive Power BI dashboard highlighting salary, skills, and career insights from a survey of data professionals.', imageSrc: createSvgImage('Power BI Dashboard', '#7c3aed', '#0ea5e9'), link: 'https://github.com/Nima-vd/Data-Professional-Survey-PowerBI', demo: null, problem: 'Turn a broad survey into an accessible view of data-career patterns.', dataset: 'Survey data from data professionals.', tools: 'Power BI, data modeling, dashboard design, and visual analysis.', methodology: 'Organize survey dimensions into interactive views that support comparison and exploration.', dataCleaning: 'Prepare survey fields and categories so comparisons remain consistent across visuals.', analysis: 'Compare salary, skills, and career context through interactive dashboard views.', insights: 'The dashboard makes salary, skills, and career context easier to compare.', value: 'Shows how a broad survey can become a useful decision-support surface.', challenges: 'Presenting varied survey responses without obscuring important differences.', learned: 'How information design affects the usefulness of a business dashboard.' },
  { title: 'Economic Indicators Dashboard', tag: 'Streamlit', category: 'Streamlit', description: 'A Streamlit dashboard analysing GDP growth, inflation, and remittance trends over a multi-year period.', imageSrc: createSvgImage('Economic Dashboard', '#10b981', '#0f766e'), link: 'https://github.com/Nima-vd/Nepal-Economic-Dashboard', demo: null, problem: 'Make long-term economic indicators easier to explore together through an interactive dashboard.', dataset: 'Economic indicator time-series data from 2000 to 2023.', tools: 'Python, Streamlit, data preparation, and interactive visualization.', methodology: 'Bring multiple indicators into one navigable dashboard for trend comparison.', dataCleaning: 'Align indicator names, years, and values to support consistent time-series views.', analysis: 'Compare GDP growth, inflation, and remittance trends across the shared period.', insights: 'Users can inspect multiple indicators across the same time window and identify key shifts.', value: 'Creates a clearer starting point for contextual economic analysis and stakeholder review.', challenges: 'Making indicators with different scales readable in one dashboard.', learned: 'How interactive controls can make longitudinal analysis more approachable.' },
]

function ProjectCard({ project, index }) {
  const [expanded, setExpanded] = useState(false)
  return (
    <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ delay: index * 0.07 }} className="group bg-surface-container-lowest border border-outline-variant/30 rounded-2xl overflow-hidden project-card" style={{ perspective: 900 }}>
      <div className="aspect-video bg-surface-container-high overflow-hidden relative">
        <img alt={`${project.title} project preview`} loading="lazy" decoding="async" className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" src={project.imageSrc} />
        <div className="absolute inset-0 bg-gradient-to-t from-[#09171d]/90 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
        <span className="absolute top-4 right-4 bg-primary text-on-primary px-3 py-1 rounded-full text-xs font-label-sm">{project.tag}</span>
      </div>
      <div className="p-6">
        <h3 className="font-headline-sm text-headline-sm text-on-surface mb-2">{project.title}</h3>
        <p className="font-body-md text-body-md text-on-surface-variant mb-5">{project.description}</p>
        <div className="flex items-center gap-4 flex-wrap">
          <MagneticButton className="text-primary font-label-md text-label-md inline-flex items-center gap-2" href={project.link} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15} /></MagneticButton>
          {project.demo ? <a className="text-secondary font-label-md text-label-md inline-flex items-center gap-2 hover:text-primary transition-colors" href={project.demo} target="_blank" rel="noreferrer">Live demo <ExternalLink size={14} /></a> : <span className="text-secondary/70 font-label-sm text-label-sm inline-flex items-center gap-2"><ExternalLink size={14} /> Demo not published</span>}
          <button type="button" onClick={() => setExpanded(open => !open)} aria-expanded={expanded} className="ml-auto text-secondary hover:text-primary transition-colors" aria-label={`${expanded ? 'Hide' : 'Show'} ${project.title} case study`}><ChevronDown size={18} className={`transition-transform ${expanded ? 'rotate-180' : ''}`} /></button>
        </div>
        <AnimatePresence initial={false}>
          {expanded && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><dl className="case-study-grid mt-6 pt-5 border-t border-outline-variant/20">{[['Problem', project.problem], ['Dataset', project.dataset], ['Tools used', project.tools], ['Methodology', project.methodology], ['Data cleaning', project.dataCleaning], ['Analysis', project.analysis], ['Key insights', project.insights], ['Business impact', project.value], ['Challenges', project.challenges], ['What I learned', project.learned]].map(([label, text]) => <div key={label}><dt className="font-label-sm text-label-sm text-primary">{label}</dt><dd className="font-body-md text-body-md text-on-surface-variant mt-1">{text}</dd></div>)}</dl></motion.div>}
        </AnimatePresence>
      </div>
    </motion.article>
  )
}

export default function Projects() {
  const [activeFilter, setActiveFilter] = useState('All')
  const filteredProjects = useMemo(() => activeFilter === 'All' ? projects : projects.filter(project => project.category === activeFilter), [activeFilter])
  return (
    <section className="py-stack-xl bg-surface" id="projects">
      <div className="max-w-container-max mx-auto px-margin-mobile md:px-gutter">
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 mb-stack-lg"><div><p className="eyebrow">Selected work</p><h2 className="font-headline-md text-headline-md text-on-surface mt-3">Projects with a point of view.</h2><p className="text-secondary font-body-md mt-2 max-w-2xl">A focused sample of analysis, dashboards, and applications. Open a case study to see the problem, method, and business context.</p></div><div className="project-stats"><span><strong>04</strong> projects</span><span><strong>05</strong> tracks</span></div></div>
        <div className="flex gap-2 overflow-x-auto pb-3 mb-6" role="group" aria-label="Filter projects by technology">{filters.map(filter => <button type="button" key={filter} onClick={() => setActiveFilter(filter)} aria-pressed={activeFilter === filter} className={`filter-chip ${activeFilter === filter ? 'is-active' : ''}`}>{filter}</button>)}</div>
        {filteredProjects.length ? <div className="grid grid-cols-1 md:grid-cols-2 gap-stack-md">{filteredProjects.map((project, index) => <ProjectCard key={project.title} project={project} index={index} />)}</div> : <div className="empty-projects glass-panel"><p className="font-label-md text-label-md text-primary">SQL projects</p><p className="font-body-md text-body-md text-on-surface-variant mt-2">No SQL project is published in the current portfolio yet.</p></div>}
      </div>
    </section>
  )
}
